export const traduccionesES = {
    'menu-inicio': 'Inicio', 
    'menu-creadores': 'Creadores',
    'menu-acerca-de': 'Acerca de',
    'menu-destinos': 'Destinos',
    'menu-iniciar-sesion': 'Iniciar Sesión',
    'menu-registro': 'Registrarse',
    'mensaje-bienvenida': '"El viaje de tus sueños, tal como lo imaginaste, con todo lo que deseas a tu alcance."',
    'servicios': 'Servicios',
    'publicaciones': 'Publicaciones',
    'eventos': 'Eventos',
    'select-regiones': 'Selecciona tu Región',
    'select-ciudad': "Selecciona tu Ciudad",
    'select-servicios': 'Selecciona tus Servicios',
    'btn-buscar': 'Buscar',
    'creadores': 'Creadores',
    'bienvenido': 'Bienvenido de Nuevo',
    'email_placeholder':'Ingresa tu correo',
    'pass_placeholder':'Ingresa tu contraseña',
    'forgot-password':'¿Olvidaste tu contraseña?',
    'o':'O',
    'google':'Continuar con Google',
    'no-registrado':'¿No estas Registrado?',
    'crear-cuenta':'Crea una Cuenta',
    'mensaje-registro':'¿Cómo desea registrarse?',
    'reg-empresa':'Registro de Empresa',
    'reg-usuario':'Registro de Usuario',
    'title-regist-emp':'Crear un nueva cuenta de Empresa',
    '':'',
    '':'',

}