export const traduccionesEN = {
    'menu-inicio': 'Home', 
    'menu-creadores': 'Creators',
    'menu-acerca-de': 'About',
    'menu-destinos': 'Destinations',
    'menu-iniciar-sesion': 'Log In',
    'menu-resgistro': 'Register',
    'mensaje-bienvenida': '"The trip of your dreams, just as you imagined it, with everything you desire within your grasp."',
    'servicios': 'Services',
    'publicaciones': 'Latest posts',
    'eventos': 'Event Board',
    'select-regiones': 'Select your region:',
    'select-ciudad': "Select your city:",
    'select-servicios': 'Choose your desired services',
    'btn-buscar': 'Search',
    'creadores': 'Creators',
    'bienvenido': 'Welcome Back',
    'email_placeholder':'Enter your email',
    'pass_placeholder':'Enter your password',
    'forgot-password':'Forgot password?',
    'o':'OR',
    'google': 'Continue with Google',
    'no-registrado':'Not registered yet? ',
    'crear-cuenta':'Create account',
    'mensaje-registro':'How would you like to register?',
    'reg-empresa':'Enterprise Register',
    'reg-usuario':'User Register',
    'title-regist-emp':'Create New Enterprise Account',
    '':'',
}