export const traduccionesEN = {
    'menu-inicio': 'Home', 
    'menu-creadores': 'Creators',
    'menu-acerca-de': 'About',
    'menu-destinos': 'Destinations',
    'menu-iniciar-sesion': 'Log In',
    'mensaje-bienvenida': '"The trip of your dreams, just as you imagined it, with everything you desire within your grasp."',
    'servicios': 'Services',
    'publicaciones': 'Latest posts',
    'eventos': 'Event Board',
    'select-regiones': 'Select your region:',
    'select-ciudad': "Select your Department:",
    'select-servicios': 'Choose your desired services',
    'btn-buscar': 'Search',
    'creadores': 'Creators',
    'bienvenido': 'Welcome Back',
    'email_placeholder':'Enter your email',
    'pass_placeholder':'Enter your password',
    'forgot-password':'Forgot password?',
    'o':'OR',
    'google': 'Continue with Google',
    'no-registrado':'Not registered yet? ',
    'crear-cuenta':'Create account',
    'mensaje-registro':'How would you like to register?',
    'reg-empresa':'Enterprise Register',
    'reg-usuario':'User Register',
    'title-regist-emp':'Create New Enterprise Account',
    'title-regist-user':'Create New User Account',
    'nombre-completo':'Full Name',
    'numero-cel':'Phone Number',
    'email_confirm_placeholder':'Confirm your Email',
    'pass_confirm_placeholder':'Confirm Password',
    'nombre-negocio':'Business Name',
    'numero-negocio':'Business Number',
    'nit-negocio':'Business ID NIT / Tax Number',
    'title-services':'Category of the service',
    'post-services':'Post your services',
    'registro':'Register',
    'alojamiento':'Accommodation and Hospitality',
    'restaurantes':'Restaurants and Gastronomy',
    'departamento':'Department',
    'ciudad':'City',
    'servicio':'Description of the service',
    'guardar':'Post',
    'textarea':'Remember to write days, cost, and all relevant details',
    'hoteles':'Accommodation and Hospitality',
    'restaurante':'Restaurants and Gastronomy',
    'agencias':'Agencies and Tour Operators',
    'cultura':'Cultural and Heritage Tourism',
    'title-mision':'Mission',
    'title-vision':'Vision',
    'mision':'To facilitate travel planning in Region 5 of Colombia through a bilingual, centralized, and accessible digital platform that connects tourists with local service providers, promotes ecotourism, and boosts the visibility of small businesses in the digital space.',
    'vision':'To become the leading digital platform for sustainable and cultural tourism in Colombia, recognized for its innovation, social impact, and commitment to local economic development, offering unique experiences to both national and international tourists.',
    'ms-posts':'There are no publications available yet',
    'about':'ABOUT US',
    'about-info':'We are Caribe Dreams a digital initiative born from young minds passionate about tourism, technology, and sustainable development. We believe that traveling should be simple, safe, and enriching. That’s why we created a platform that connects travelers with the best of Region 5: its people, its landscapes, its culture, and its services. We want you to experience Colombia like never before… with everything you dream of, just one click away.',
    '':'',
    '':'',
    '':'',
    '':'',

}