export const traduccionesES = {
    'menu-inicio': 'Inicio', 
    'menu-creadores': 'Creadores',
    'menu-acerca-de': 'Acerca de',
    'menu-destinos': 'Destinos',
    'menu-iniciar-sesion': 'Iniciar Sesión',
    'mensaje-bienvenida': '"El viaje de tus sueños, tal como lo imaginaste, con todo lo que deseas a tu alcance."',
    'servicios': 'Servicios',
    'publicaciones': 'Publicaciones',
    'eventos': 'Eventos',
    'select-regiones': 'Selecciona tu Región:',
    'select-ciudad': "Selecciona tu Departamento:",
    'select-servicios': 'Selecciona tus Servicios:',
    'btn-buscar': 'Buscar',
    'creadores': 'Creadores',
    'bienvenido': 'Bienvenido de Nuevo',
    'email_placeholder':'Ingresa tu Correo',
    'pass_placeholder':'Ingresa tu Contraseña',
    'forgot-password':'¿Olvidaste tu Contraseña?',
    'o':'O',
    'google':'Continuar con Google',
    'no-registrado':'¿No estas Registrado?',
    'crear-cuenta':'Crea una Cuenta',
    'mensaje-registro':'¿Cómo desea registrarse?',
    'reg-empresa':'Registro de Empresa',
    'reg-usuario':'Registro de Usuario',
    'title-regist-emp':'Crear un nueva cuenta de Empresa',
    'title-regist-user':'Crear nueva cuenta de Usuario',
    'nombre-completo':'Nombre Completo',
    'numero-cel':'Número de Celular',
    'email_confirm_placeholder':'Confirma tu Correo',
    'pass_confirm_placeholder':'Confirma tu Contraseña',
    'nombre-negocio':'Nombre del Negocio',
    'numero-negocio':'Número del Negocio',
    'nit-negocio':'Número de identificación comercial (NIT)',
    'title-services':'Categoría de Servicios',
    'post-services':'Publica tus Servicios',
    'registro':'Registrarse',
    'alojamiento':'Alojamiento y hospitalidad',
    'restaurantes':'Restaurantes y gastronomía',
    'departamento':'Departamento',
    'ciudad':'Ciudad',
    'servicio':'Descripción del servicio',
    'guardar':'Publicar',
    'textarea':'Recuerda escribir días, costos y todos los detalles relevantes.',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',


}