export const traduccionesEN = {
    'menu-inicio': 'Home', 
    'menu-creadores': 'Creators',
    'menu-acerca-de': 'About',
    'menu-destinos': 'Destinations',
    'menu-iniciar-sesion': 'Log In',
    'mensaje-bienvenida': '"The trip of your dreams, just as you imagined it, with everything you desire within your grasp."',
    'servicios': 'Services',
    'publicaciones': 'Latest posts',
    'eventos': 'Event Board',
    'select-regiones': 'Select your region:',
    'select-ciudad': "Select your Department:",
    'select-servicios': 'Choose your desired services',
    'btn-buscar': 'Search',
    'creadores': 'Creators',
    'bienvenido': 'Welcome Back',
    'email_placeholder':'Enter your email',
    'pass_placeholder':'Enter your password',
    'forgot-password':'Forgot password?',
    'o':'OR',
    'google': 'Continue with Google',
    'no-registrado':'Not registered yet? ',
    'crear-cuenta':'Create account',
    'mensaje-registro':'How would you like to register?',
    'reg-empresa':'Enterprise Register',
    'reg-usuario':'User Register',
    'title-regist-emp':'Create New Enterprise Account',
    'title-regist-user':'Create New User Account',
    'nombre-completo':'Full Name',
    'numero-cel':'Phone Number',
    'email_confirm_placeholder':'Confirm your Email',
    'pass_confirm_placeholder':'Confirm Password',
    'nombre-negocio':'Business Name',
    'numero-negocio':'Business Number',
    'nit-negocio':'Business ID NIT / Tax Number',
    'title-services':'Category of the service',
    'post-services':'Post your services',
    'registro':'Register',
    'alojamiento':'Accommodation and Hospitality',
    'restaurantes':'Restaurants and Gastronomy',
    'departamento':'Department',
    'ciudad':'City',
    'servicio':'Description of the service',
    'guardar':'Post',
    'textarea':'Remember to write days, cost, and all relevant details',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
}